version: '3.8'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      CONFIG_MONGODB_ADMINUSERNAME: root
      CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - "27017:27017"
  
  app:
    depends_on:
      - mongo
    container_name: test_shopper_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env